### ISSUE TITLE
2.1 Checklist

### ISSUE THREAD

**Issue by georgebutter** [Elkfox/Concrete#23]
- [x]  #6 Collection view links
- [x]  #11 Theme settings cleanup
- [x]  #13 Data attribute cart selectors
- [x]  #16 Popups update, issues with < iOS 9
- [x] #20 Duplicated logo settings
- [x] #21 Form cleanup
- [x] #55 Clean up account layout
- [x]  #24 Toggled popover nav
- [x]  #47 Revamped flex grid
- [ ] #53 Revamped search layout
- [x] #62 Recover form feedback 
- [ ] #73 Updated docs
- [x] #17 Cartfox 3.0
